const menuItems=[
{id:1,name:'Truffle Margherita Pizza',category:'Pizza',veg:'veg',price:14,rating:4.8,spicy:'Mild',desc:'Stone-baked pizza with basil and mozzarella.',img:'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=800&q=80'},
{id:2,name:'Smoky Chicken Burger',category:'Burger',veg:'non-veg',price:12,rating:4.7,spicy:'Medium',desc:'Grilled chicken patty with smoked sauce.',img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80'},
{id:3,name:'Royal Dum Biryani',category:'Biryani',veg:'non-veg',price:16,rating:4.9,spicy:'Hot',desc:'Aromatic basmati with saffron and spices.',img:'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80'},
{id:4,name:'Paneer Kathi Roll',category:'Rolls',veg:'veg',price:10,rating:4.6,spicy:'Medium',desc:'Soft roll with grilled paneer and mint chutney.',img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80'},
{id:5,name:'Schezwan Noodles',category:'Chinese',veg:'veg',price:11,rating:4.5,spicy:'Hot',desc:'Wok tossed noodles with fresh vegetables.',img:'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80'},
{id:6,name:'Chocolate Lava Cake',category:'Desserts',veg:'veg',price:8,rating:4.9,spicy:'None',desc:'Warm chocolate center and vanilla scoop.',img:'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80'},
{id:7,name:'Citrus Mint Cooler',category:'Drinks',veg:'veg',price:6,rating:4.4,spicy:'None',desc:'Refreshing cooler with citrus and mint.',img:'https://images.unsplash.com/photo-1551024709-8f23befc6cf7?auto=format&fit=crop&w=800&q=80'}
];
const getCart=()=>JSON.parse(localStorage.getItem('foodfly_cart')||'[]');
const setCart=(c)=>{localStorage.setItem('foodfly_cart',JSON.stringify(c));updateCartCount();};
const updateCartCount=()=>{const count=getCart().reduce((a,b)=>a+b.qty,0);document.querySelectorAll('#cart-count').forEach(e=>e.textContent=count);};
const addToCart=(id)=>{const c=getCart();const x=c.find(i=>i.id===id);if(x)x.qty++;else c.push({id,qty:1});setCart(c);};
const renderCards=(target,data)=>{if(!target)return;target.innerHTML=data.map(item=>`<article class='card'>${item.rating>4.7?"<span class='badge'>Best Seller</span>":''}<img class='food-img' src='${item.img}' alt='${item.name}'/><div class='meta'><strong>${item.name}</strong><button onclick='toggleFav(${item.id},this)' class='btn btn-outline'>♡</button></div><p>${item.desc}</p><div class='meta'><span>$${item.price}</span><span>⭐ ${item.rating} • ${item.spicy}</span></div><div class='meta'><span class='badge ${item.veg}'>${item.veg}</span><button class='btn btn-primary' onclick='addToCart(${item.id})'>Add to Cart</button></div></article>`).join('');};
const menuGrid=document.getElementById('menu-grid');
const applyFilters=()=>{if(!menuGrid)return;let data=[...menuItems];const q=(document.getElementById('search')?.value||'').toLowerCase();const cat=document.getElementById('category-filter')?.value||'all';const veg=document.getElementById('veg-filter')?.value||'all';const sort=document.getElementById('sort')?.value||'default';if(q)data=data.filter(i=>i.name.toLowerCase().includes(q)||i.desc.toLowerCase().includes(q));if(cat!=='all')data=data.filter(i=>i.category===cat);if(veg!=='all')data=data.filter(i=>i.veg===veg);if(sort==='price-asc')data.sort((a,b)=>a.price-b.price);if(sort==='price-desc')data.sort((a,b)=>b.price-a.price);if(sort==='rating')data.sort((a,b)=>b.rating-a.rating);renderCards(menuGrid,data);};
['search','category-filter','veg-filter','sort'].forEach(id=>document.getElementById(id)?.addEventListener('input',applyFilters));
['category-filter','veg-filter','sort'].forEach(id=>document.getElementById(id)?.addEventListener('change',applyFilters));
renderCards(document.getElementById('best-sellers'),menuItems.slice(0,3));applyFilters();updateCartCount();
const renderCart=()=>{const box=document.getElementById('cart-items');if(!box)return;const cart=getCart();if(!cart.length){box.innerHTML='<p>Your cart is empty.</p>';calcTotal();return;}box.innerHTML=cart.map(c=>{const item=menuItems.find(i=>i.id===c.id);return `<article class='card'><div class='meta'><strong>${item.name}</strong><button onclick='removeItem(${item.id})' class='btn btn-outline'>Remove</button></div><p>$${item.price} x ${c.qty}</p><div class='meta'><button class='btn btn-outline' onclick='qty(${item.id},-1)'>-</button><span>${c.qty}</span><button class='btn btn-outline' onclick='qty(${item.id},1)'>+</button></div></article>`}).join('');calcTotal();};
const qty=(id,n)=>{const c=getCart();const x=c.find(i=>i.id===id);if(!x)return;x.qty+=n;if(x.qty<=0)c.splice(c.indexOf(x),1);setCart(c);renderCart();};
const removeItem=(id)=>{setCart(getCart().filter(i=>i.id!==id));renderCart();};
const calcTotal=()=>{const cart=getCart();let sub=0;cart.forEach(c=>{const it=menuItems.find(i=>i.id===c.id);sub+=it.price*c.qty;});let del=cart.length?3:0;let total=sub+del;if(localStorage.getItem('coupon')==='NEW20')total*=0.8;document.getElementById('subtotal')&&(document.getElementById('subtotal').textContent=`$${sub.toFixed(2)}`);document.getElementById('delivery')&&(document.getElementById('delivery').textContent=`$${del.toFixed(2)}`);document.getElementById('total')&&(document.getElementById('total').textContent=`$${total.toFixed(2)}`);const summary=document.getElementById('checkout-summary');if(summary)summary.textContent=cart.length?cart.map(c=>`${menuItems.find(i=>i.id===c.id).name} x${c.qty}`).join(', '):'No items selected yet.';};
const applyCoupon=()=>{const code=document.getElementById('coupon')?.value.trim().toUpperCase();if(code==='NEW20'){localStorage.setItem('coupon','NEW20');alert('Coupon applied: 20% OFF');}else{localStorage.removeItem('coupon');alert('Invalid coupon');}calcTotal();};
const toggleFav=(id,btn)=>{btn.textContent=btn.textContent==='♡'?'♥':'♡'};
const repeatOrder=()=>{localStorage.setItem('foodfly_cart',localStorage.getItem('foodfly_last_order')||'[]');alert('Last order repeated!');};
window.addEventListener('beforeunload',()=>localStorage.setItem('foodfly_last_order',JSON.stringify(getCart())));
renderCart();calcTotal();
const countdown=document.getElementById('offer-countdown');if(countdown){let secs=7200;setInterval(()=>{const h=Math.floor(secs/3600),m=Math.floor((secs%3600)/60),s=secs%60;countdown.textContent=`Offer ends in ${h}h ${m}m ${s}s`;secs=secs>0?secs-1:0;},1000)}
